### ISSUE TITLE
[BUG] Unable to generate OpenAPI3.0 specification. It is coming Blank

### ISSUE THREAD

**Issue by Siddharth084** [WillEastbury/odata-openapi#7] opened 2024-07-01 09:23 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

** OData Payload for diagnosis **
Please paste or link to your odata payload that was processed.

**Additional context**

**Comment by MartinPankraz** [comment] 2024-07-02 11:09
@Siddharth084 please shared details of your request.

**Comment by MartinPankraz** [comment] 2024-07-02 11:10
duplicate of #8

**Closed as completed by MartinPankraz** 2024-07-02 11:10 UTC
Labels: bug
